server:
  port: 9300
spring:
  profiles:
    active: prod
  thymeleaf:
    enabled: true
    cache: false
    suffix: .html
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
